test_data:
  directory: "data/raw/Test"
  img_height: 224
  img_width: 224
  batch_size: 32
  class_mode: "binary"

models_to_evaluate:
  - name: "DenseNet Model"
    path: "experiments/individual_models/densenet/densenet_final.keras"

  - name: "Xception Model"
    path: "experiments/individual_models/xception/xception_final.keras"

  - name: "ResNet Model"
    path: "experiments/individual_models/resnet/resnet_final.keras"

metrics:
  threshold: 0.5
