test_data:
  directory: "data/processed/Test"
  img_height: 224
  img_width: 224
  batch_size: 32
  class_mode: "binary"

# cambiar segun lo necesario
models_to_evaluate:
  # - name: "DenseNet Model"
  #   path: "experiments/individual_models/densenet/results/densenet_final.h5"

  # - name: "Xception Model"
  #   path: "experiments/individual_models/xception/results/xception_final.h5"

  # - name: "ResNet Model"
  #   path: "experiments/individual_models/resnet/results/resnet_final.h5"

metrics:
  threshold: 0.5
